[project]
name = "photo-2-dicom-v5-0"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colorlog>=6.9.0",
    "dbutils>=3.1.2",
    "numpy>=2.3.3",
    "oracledb>=3.4.2",
    "pillow>=11.3.0",
    "pydicom>=3.0.1",
    "pyinstaller>=6.19.0",
    "pyodbc>=5.2.0",
    "requests>=2.32.5",
    "xpinyin>=0.7.7",
]
